### ISSUE TITLE
网页在Windows下的解析问题

### ISSUE THREAD

**Issue by DavidSHwang** [weNKers/OurBook#16]
网页的html标签中带有错误的语言参数：

`<html lang="en-US">`

当浏览者安装了“进阶字体设置”插件对不同语种定义不同字体后，就造成网页字体被Chrome错误地解析，对整个网页指定拉丁字体，而CJK字符fallback到中易宋体，显示效果不佳：

![1](https://user-images.githubusercontent.com/24728204/41886432-ebd35216-792e-11e8-99c0-94782dba30c0.png)

而如果删除该参数，或改为：

`<html lang="zh-CN">`

Chrome就能够选择预设的简中字体（此处为思源黑体）：

![3](https://user-images.githubusercontent.com/24728204/41886545-5e04e62e-792f-11e8-830e-da5b3dbe1dc0.png)

望修复！

**Comment by Liyuk** [comment]
已收到

**Comment by Liyuk** [comment]
已修复，感谢建议
